import Image from 'next/image'
import Head from 'next/head'
import Leaf from '../components/svg/Leaf'
import styles from '../styles/Home.module.scss'
import { Post } from '../components/Post'
import { posts } from '../GetAllPosts'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Environment 1st</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.intro}>
          <div className={styles.header}>
            <Image
              src="/svg/earth.svg"
              height={300}
              width={300}
              alt="Earth"
            />
            <div>
              <h1 className="accent-secondary">
                The Earth needs your help.
              </h1>
              <h3>
                Find out how you can contribute and change things for the better.
              </h3>
            </div>
          </div>
        </div>
        <div className="spacer--large"/>
        <h2 className="side-padding">
          Recent disasters
        </h2>
        <div className={ styles.posts }>
          { posts.map((post) => (
            <Post
              key={ post.link }
              post={ post }
            />
          )) }          
        </div>
      </main>
    </div>
  )
}
