import Image from 'next/image'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Post } from '../components/Post'
import { posts } from '../GetAllPosts'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.intro}>
          <div className={styles.header}>
            <h1>
              The Earth needs your help.
            </h1>
            <p>
              Find out how you can contribute and change things for the better.
            </p>
          </div>
          <Image
            src="/img/jungle.jpeg"
            alt="Jungle"
            layout="responsive"
            height={ 300 }
            width={ 300 } 
          />
        </div>
        <div className={ styles.posts }>
          { posts.map((post) => (
            <Post
              key={ post.link }
              post={ post }
            />
          )) }          
        </div>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
